AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Max: 50
  ExcludedMethods: ['describe', 'context', 'it', 'shared_examples', 'define', 'draw']

Metrics/ClassLength:
  Max: 200

Metrics/ModuleLength:
  Max: 150
