AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/AbcSize:
  Max: 25

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/PerceivedComplexity:
  Max: 10

Metrics/MethodLength:
  Max: 25

Metrics/BlockLength:
  Max: 30
  ExcludedMethods:
    - describe

Metrics/ClassLength:
  Max: 120

Metrics/ModuleLength:
  Max: 150
