Style/Documentation:
  Enabled: false

Style/Lambda:
  Enabled: false

Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Max: 30
  ExcludedMethods:
    - describe
    - shared_examples

Metrics/LineLength:
  Max: 100

Metrics/ModuleLength:
  Max: 150
